
create table
  founderx_days (
    id bigint generated by default as identity,
    description text null,
    created_at timestamp with time zone not null default now(),
    primary key (id)
  );


--  id, user, day, note, created_at
create table
  founderx_notes (
    id bigint generated by default as identity,
    user_id uuid not null references auth.users on delete cascade,
    day_id bigint not null references founderx_days on delete cascade,
    note text not null,
    created_at timestamp with time zone not null default now(),
    primary key (id)
  );